apiVersion: v1
kind: Service
metadata:
  name: mianatra-backend
  labels:
    app.kubernetes.io/name: mianatra-backend
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mianatra-backend
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8000
      targetPort: http
