version: '3.8'

services:
  web:
    build: .
    ports:
      - "5321:5000"  
    volumes:
      - .:/app
      - uploads:/app/static/uploads
    environment:
      - DB_HOST=db
      - DB_NAME=pdf_courses
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - FLASK_DEBUG=1
    depends_on:
      - db
    networks:
      - backend_network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=pdf_courses
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pdf_courses"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  uploads:

networks:
  backend_network:
    driver: bridge
    internal: true  