apiVersion: v1
kind: Secret
metadata:
  name: mianatra-secret
  labels:
    app.kubernetes.io/name: mianatra-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
  DATABASE_URL: "postgresql+psycopg2://postgres:postgres@mianatra-postgres:5432/pdf_courses"
  SECRET_KEY: "change-this-secret-key-before-production"
  DEFAULT_ADMIN_USERNAME: "admin"
  DEFAULT_ADMIN_PASSWORD: "admin123"
