apiVersion: v1
kind: Service
metadata:
  name: mianatra-postgres
  labels:
    app.kubernetes.io/name: mianatra-postgres
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mianatra-postgres
    app.kubernetes.io/component: database
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
