apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mianatra-hpa
  namespace: mianatra
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mianatra-web
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70