apiVersion: v1
kind: Secret
metadata:
  name: mianatra-secrets
  namespace: mianatra
type: Opaque
stringData:
  DB_HOST: "mianatra-db"
  DB_USER: "postgres"
  DB_PASSWORD: "votre-mot-de-passe-complexe"
  SECRET_KEY: "votre-cle-secrete-flask"